version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: bigdata_postgres
    environment:
      POSTGRES_DB: bigdata
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/data